plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /:title/

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

url: https://vikaslamba99.github.io
title: Vikas Lamba
repo: weakish/micro-gh-page
